### ISSUE TITLE
ESM is missing for @webassemblyjs/ast

### ISSUE THREAD

**Issue by d3lm** [xtuc/webassemblyjs#1145]
I noticed that starting from `1.11.5` the `esm` folder is missing so that the `module` entry point, which is `esm/index.js` doesn't work.

<img width="526" alt="image" src="https://github.com/xtuc/webassemblyjs/assets/12571019/a13a13a9-f02d-493c-9ee9-108a91d28132">

**Comment by jbanovs** [comment]
I have the same issue for other packages trying to build my code with Vite.

Error message the same for all:
`Failed to resolve entry for package "@webassemblyjs/leb128". The package may have incorrect main/module/exports specified in its package.json.`

It because there is `"module": "esm/index.js"` in package.json but there is not such folder.

I managed to resolve the issue rolling back from last patch
```
  "pnpm": {
    "overrides": {
      "@webassemblyjs/helper-numbers": "1.11.4",
      "@webassemblyjs/helper-wasm-bytecode": "1.12.0",
      "@webassemblyjs/helper-api-error": "1.12.0",
      "@webassemblyjs/ieee754": "1.12.0",
      "@webassemblyjs/utf8": "1.12.0",
      "@webassemblyjs/leb128": "1.12.0"
    }
  }
```

**Comment by xtuc** [comment]
That should be fixed now.
