### ISSUE TITLE
Simplify the AST traversal

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#263]
I'm in the process of adding a new transform that denormalizes type references as per #242. It feels like more work than it should be, when you add a new node type, or node property you have to update the AST traversal to accommodate this structural change (adding extra traversal logic and node type information).

I'd like to refactor so that it traverses all object properties automatically, invoking the callback for all objects that have a `type` property. Can anyone see a problem with this?

Also, should the AST transforms be moved into the `@webassemblyjs/ast` package? I've added a few in wasm-parser (e.g. #262), I'd be happy to move them into a common package.

**Comment by xtuc** [comment]
Yes, that's a good question. 

I can see two solutions for that:
- Refactor to have more consistent nodes (with `value` and `body` fields) but some nodes like `if` would still require some manual tweaking
- Continuing the traversal using `Object.keys(node)` but that would require a bit of refactor because some nodes uses `number` instead of `NumberLiteral` as a leaf.

**Comment by xtuc** [comment]
> can you give an example of the number vs NumberLiteral issue?

Thinking about it a bit more, we probably don't need it. The only limitation is that you can't have a visitor for all number or strings.

Example: https://github.com/xtuc/webassemblyjs/blob/master/types/AST.js#L374-L380. If you visit `NumberLiteral` those won't show up.
