### ISSUE TITLE
Clarify License of packages/leb128

### ISSUE THREAD

**Issue by stigi** [xtuc/webassemblyjs#463]
Hi there,

I noticed that the License in `package.json` of packages/leb128 states `MIT` while `LICENSE.txt` contains the Apache License.

This needs some clarification.

CC @papandreou who might have added the `MIT` statement in 6251679a8817f300ca9291acd70be2bcd263cdac by mistake.

**Comment by papandreou** [comment]
@stigi, whoopsie, when I made that PR I didn't notice that the contained leb123 package had [its own license](https://github.com/xtuc/webassemblyjs/blob/master/packages/leb128/LICENSE.txt), I just assumed that the [top level LICENSE](https://github.com/xtuc/webassemblyjs/blob/master/LICENSE) applied to all of the contained packages.

I only made the PR because our automatic license-checking tool was complaining that `ieee754` didn't have a license at all, so I'm no authority on what the licenses actually are :)

**Comment by hrieke** [comment]
From here perhaps?
https://www.npmjs.com/package/leb

**Comment by xtuc** [comment]
Would you mind sending a PR?

**Comment by xtuc** [comment]
license has been clarified since
