### ISSUE TITLE
Missing licenses in 1.7.10

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [xtuc/webassemblyjs#468]
Hello,

I'm not sure what happened, but it looks like the following packages previously had license files but are now missing them in version 1.7.10:

- jswasm-edit
- jswasm-parser
- jswast-parser
- jswast-printer

Can these license files be readded?

Thanks :)

**Comment by xtuc** [comment]
Interesting, you can see the difference here:
- before: https://unpkg.com/@webassemblyjs/wasm-edit@1.7.9/
- after: https://unpkg.com/@webassemblyjs/wasm-edit@1.7.10/

I'm going to investigate and publish a new version asap.

**Comment by xtuc** [comment]
Fixed in:
- https://unpkg.com/@webassemblyjs/wasm-edit@1.7.11/
- https://unpkg.com/@webassemblyjs/wasm-parser@1.7.11/
- https://unpkg.com/@webassemblyjs/wast-parser@1.7.11/
- https://unpkg.com/@webassemblyjs/wast-printer@1.7.11/

Thanks for your report and sorry I don't know what happened with our publishing.

**Comment by Bosch-Eli-Black** [comment]
No worries! Thanks for the fix :)
